import React, { useEffect, useState } from "react";
import { useLanguage } from "../../../context/LanguageContext";
import ProfileDropdown from "../../common/ProfileDropdown";

const defaultValues = {
  name: "",
  email: "",
  password: "",
  status: "Active",
  workflowRole: "",
  notes: "",
};

const UserForm = ({
  mode = "add",
  initialValues,
  onSubmit,
  onCancel,
  submitLabel,
  isSubmitting = false,
}) => {
  const { t } = useLanguage();
  const [formValues, setFormValues] = useState({
    ...defaultValues,
    ...initialValues,
  });

  const workflowRoles = [
    { value: "Question Gatherer", label: t('admin.userManagement.roles.questionGatherer') },
    { value: "Question Creator", label: t('admin.userManagement.roles.questionCreator') },
    { value: "Processor", label: t('admin.userManagement.roles.processor') },
    { value: "Question Explainer", label: t('admin.userManagement.roles.questionExplainer') },
  ];
  
  const statusOptions = [
    { value: "Active", label: t('admin.userManagement.status.active') },
    { value: "Suspended", label: t('admin.userManagement.status.suspended') },
  ];

  useEffect(() => {
    setFormValues({ ...defaultValues, ...initialValues });
  }, [initialValues]);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setFormValues((prev) => ({ ...prev, [name]: value }));
  };

  const handleDropdownChange = (fieldName) => (value) => {
    setFormValues((prev) => ({ ...prev, [fieldName]: value }));
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    onSubmit?.(formValues);
  };

  const actionLabel =
    submitLabel || (mode === "edit" ? t('admin.addUser.form.buttons.saveChanges') : t('admin.addUser.form.buttons.saveUser'));

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      <div className="grid gap-7 md:grid-cols-2">
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">
            {t('admin.addUser.form.fields.userName')} <span className="text-[#ED4122]">*</span>
          </span>
          <input
            required
            name="name"
            value={formValues.name}
            onChange={handleChange}
            placeholder={t('admin.addUser.form.placeholders.enterName')}
            className="h-[59px] w-full max-w-[476px] rounded-[12px] border border-[#032746]/20 bg-white px-4 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
          />
        </label>
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">
            {t('admin.addUser.form.fields.emailAddress')} <span className="text-[#ED4122]">*</span>
          </span>
          <input
            required
            type="email"
            name="email"
            value={formValues.email}
            onChange={handleChange}
            placeholder={t('admin.addUser.form.placeholders.enterEmail')}
            className="h-[59px] w-full max-w-[476px] rounded-[12px] border border-[#032746]/20 bg-white px-4 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
          />
        </label>
        {mode === "add" && (
          <label className="flex flex-col gap-2">
            <span className="text-[16px] font-roboto font-normal text-oxford-blue">
              {t('admin.addUser.form.fields.password')}
            </span>
            <input
              name="password"
              value={formValues.password}
              onChange={handleChange}
              placeholder={t('admin.addUser.form.placeholders.autoGenerated')}
              className="h-[59px] w-full max-w-[476px] rounded-[12px] border border-[#032746]/20 bg-white px-4 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
            />
          </label>
        )}
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">{t('admin.addUser.form.fields.status')}</span>
          <div className="w-full max-w-[476px]">
            <ProfileDropdown
              value={formValues.status}
              options={statusOptions}
              onChange={handleDropdownChange('status')}
              className="w-full max-w-[476px]"
            />
          </div>
        </label>
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">
            {t('admin.addUser.form.fields.workflowRole')} <span className="text-[#ED4122]">*</span>
          </span>
          <div className="w-full max-w-[476px]">
            <ProfileDropdown
              value={formValues.workflowRole}
              options={[
                { value: '', label: t('admin.addUser.form.placeholders.selectWorkflowRole') },
                ...workflowRoles
              ]}
              onChange={handleDropdownChange('workflowRole')}
              placeholder={t('admin.addUser.form.placeholders.selectWorkflowRole')}
              className="w-full max-w-[476px]"
            />
          </div>
        </label>
      </div>

      <footer className="flex flex-col-reverse gap-3 pt-6 sm:flex-row sm:justify-end">
        <button
          type="button"
          onClick={onCancel}
          className="h-[44px] rounded-[10px] border border-[#E5E7EB] px-6 text-[16px] font-roboto font-medium leading-[24px] text-oxford-blue transition hover:bg-[#F3F4F6]"
        >
          {t('admin.addUser.form.buttons.cancel')}
        </button>
        <button
          type="submit"
          disabled={isSubmitting}
          className="h-[44px] rounded-[10px] bg-[#ED4122] px-6 text-[16px] font-roboto font-medium leading-[24px] text-white transition hover:bg-[#d43a1f] disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? "Saving..." : actionLabel}
        </button>
      </footer>
    </form>
  );
};

export default UserForm;


