import React, { useEffect, useState } from "react";
import { useLanguage } from "../../../context/LanguageContext";
import { dropdownArrowAdmin } from "../../../assets/svg";

const defaultValues = {
  name: "",
  email: "",
  password: "",
  status: "Active",
  workflowRole: "",
  notes: "",
};

const UserForm = ({
  mode = "add",
  initialValues,
  onSubmit,
  onCancel,
  submitLabel,
  isSubmitting = false,
}) => {
  const { t } = useLanguage();
  const [formValues, setFormValues] = useState({
    ...defaultValues,
    ...initialValues,
  });

  const workflowRoles = [
    { value: "Question Gatherer", label: t('admin.userManagement.roles.questionGatherer') },
    { value: "Question Creator", label: t('admin.userManagement.roles.questionCreator') },
    { value: "Processor", label: t('admin.userManagement.roles.processor') },
    { value: "Question Explainer", label: t('admin.userManagement.roles.questionExplainer') },
  ];
  
  const statusOptions = [
    { value: "Active", label: t('admin.userManagement.status.active') },
    { value: "Suspended", label: t('admin.userManagement.status.suspended') },
  ];

  useEffect(() => {
    setFormValues({ ...defaultValues, ...initialValues });
  }, [initialValues]);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setFormValues((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    onSubmit?.(formValues);
  };

  const actionLabel =
    submitLabel || (mode === "edit" ? t('admin.addUser.form.buttons.saveChanges') : t('admin.addUser.form.buttons.saveUser'));

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      <div className="grid gap-7 md:grid-cols-2">
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">
            {t('admin.addUser.form.fields.userName')} <span className="text-[#ED4122]">*</span>
          </span>
          <input
            required
            name="name"
            value={formValues.name}
            onChange={handleChange}
            placeholder={t('admin.addUser.form.placeholders.enterName')}
            className="h-[59px] w-full max-w-[476px] rounded-[12px] border border-[#032746]/20 bg-white px-4 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
          />
        </label>
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">
            {t('admin.addUser.form.fields.emailAddress')} <span className="text-[#ED4122]">*</span>
          </span>
          <input
            required
            type="email"
            name="email"
            value={formValues.email}
            onChange={handleChange}
            placeholder={t('admin.addUser.form.placeholders.enterEmail')}
            className="h-[59px] w-full max-w-[476px] rounded-[12px] border border-[#032746]/20 bg-white px-4 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
          />
        </label>
        {mode === "add" && (
          <label className="flex flex-col gap-2">
            <span className="text-[16px] font-roboto font-normal text-oxford-blue">
              {t('admin.addUser.form.fields.password')}
            </span>
            <input
              name="password"
              value={formValues.password}
              onChange={handleChange}
              placeholder={t('admin.addUser.form.placeholders.autoGenerated')}
              className="h-[59px] w-full max-w-[476px] rounded-[12px] border border-[#032746]/20 bg-white px-4 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
            />
          </label>
        )}
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">{t('admin.addUser.form.fields.status')}</span>
          <div className="relative w-full max-w-[476px]">
            <select
              name="status"
              value={formValues.status}
              onChange={handleChange}
              className="h-[59px] w-full appearance-none rounded-[12px] border border-[#032746]/20 bg-white px-4 pr-10 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
            >
              {statusOptions.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
            <img 
              src={dropdownArrowAdmin} 
              alt=""
              className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2"
            />
          </div>
        </label>
        <label className="flex flex-col gap-2">
          <span className="text-[16px] font-roboto font-normal text-oxford-blue">
            {t('admin.addUser.form.fields.workflowRole')} <span className="text-[#ED4122]">*</span>
          </span>
          <div className="relative w-full max-w-[476px]">
            <select
              required
              name="workflowRole"
              value={formValues.workflowRole}
              onChange={handleChange}
              className="h-[59px] w-full appearance-none rounded-[12px] border border-[#032746]/20 bg-white px-4 pr-10 text-[14px] font-roboto text-oxford-blue shadow-input outline-none"
            >
              <option value="">{t('admin.addUser.form.placeholders.selectWorkflowRole')}</option>
              {workflowRoles.map((role) => (
                <option key={role.value} value={role.value}>
                  {role.label}
                </option>
              ))}
            </select>
            <img 
              src={dropdownArrowAdmin} 
              alt=""
              className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2"
            />
          </div>
        </label>
      </div>

      <footer className="flex flex-col-reverse gap-3 pt-6 sm:flex-row sm:justify-end">
        <button
          type="button"
          onClick={onCancel}
          className="h-[44px] rounded-[10px] border border-[#E5E7EB] px-6 text-[16px] font-roboto font-medium leading-[24px] text-oxford-blue transition hover:bg-[#F3F4F6]"
        >
          {t('admin.addUser.form.buttons.cancel')}
        </button>
        <button
          type="submit"
          disabled={isSubmitting}
          className="h-[44px] rounded-[10px] bg-[#ED4122] px-6 text-[16px] font-roboto font-medium leading-[24px] text-white transition hover:bg-[#d43a1f] disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? "Saving..." : actionLabel}
        </button>
      </footer>
    </form>
  );
};

export default UserForm;


